### ISSUE TITLE
issue line 24

### ISSUE THREAD

**Issue by wbui567** [BSStudio/google-drive-recursive-ownership-transfer#1]
hello,
there is a problem on 
print("[✓]", end="")
something is wrong with the end=""
if i remove this part,
the formatted print of {folder_name} and {folder_id} are on error too.
can you give me more info for fix theses errors?

Thanks.

**Comment by KOliver94** [comment]
Hi,

Can you give us more details about the environment you use and a stack trace of the error you got?

I tested everything on a Windows 10 machine with Python 3.10 and everything worked fine.

**Comment by wbui567** [comment]
ok, thank you for your answer. I've found my issue.
I used python on macOS, but python command refer to python 2.7.
I change python command with python3.9 and it's working.
hope the script change files ownership too, because I've so many files to change ownership .^^

**Comment by KOliver94** [comment]
I hope it will. 🙂 However, the ownership changes are a bit limited (~2500 files) due to the continuous e-mail sending which cannot be disabled but I hope it will be enough for you or at least you can get things done after waiting a bit. Let me know if you need any help.

**Comment by wbui567** [comment]
I reopen here.
I test on one folder to change ownership of files inside.
the script can get the name of the folder but after the script finish but the file didn't change ownership.
do you need some screen?
